#![allow(dead_code)]
mod lib;
mod day1;
mod day2;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;
mod day10;
mod day11;
mod day12;
mod day13;
// mod day14;
// mod day16;
mod day17;
mod day18;
mod day20;
mod day21;

fn main() {
    // day1::first();
    // day1::second();
    // day2::first();
    // day2::second();
    // day3::first();
    // day3::second();
    // day4::first();
    // day4::second();
    // day5::first();
    // day5::second();
    // day6::first();
    // day6::second();
    // day7::first();
    // day7::second();
    // day8::first();
    // day8::second();
    // day9::first();
    // day9::second();
    // day10::first();
    // day10::second();
    // day11::first();
    // day11::second();
    // day12::first();
    // day12::second();
    // day13::first();
    // day13::second();
    // day14::first();
    // day14::second_new();
    // day15::first();
    // day16::first();
    // day17::first();
    // day18::first();
    // day18::second();
    // day20::first();
    // day20::first();
    day21::first();
}
